name: blake
version: 0.2.1
description: Experimental static site generator for Dart with Markdown support, mustache templates and live-reload.
homepage: https://github.com/vaetas/blake

environment:
  sdk: '>=2.8.0 <3.0.0'

executables:
  blake:

dependencies:
  ansicolor: ^1.1.1
  args: ^1.6.0
  glob: ^1.2.0
  html: ^0.14.0+4
  http_server: ^0.9.8+3
  markdown: ^3.0.0
  meta: ^1.2.4
  mustache_template: ^1.0.0+1
  path: ^1.7.0
  watcher: ^0.9.7+15
  yaml: ^2.2.1

dev_dependencies:
  analysis_options:
    git: https://github.com/vaetas/analysis_options.git
  test: ^1.15.7

scripts:
  compile:
    win:
      - mkdir build
      - dart2native bin/blake.dart -o build/blake.exe
    mac:
      - mkdir -p build
      - dart2native bin/blake.dart -o build/blake
      - tar -czf build/blake-mac.tar.gz build/blake
