name: blake
version: 0.1.0
description: Static Site Generator
homepage: https://github.com/vaetas/blake

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  markdown: ^3.0.0
  args: ^1.6.0
  ansicolor: ^1.0.5

dev_dependencies:
  pedantic: ^1.9.2
