name: anvil
version: 0.1.1
description: Static site generator for Dart with Jinja and SASS support
repository: https://github.com/ethanblake4/anvil
documentation: https://github.com/ethanblake4/anvil
homepage: https://github.com/ethanblake4/anvil

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  anvil:

dependencies:
  ansicolor: ^2.0.1
  args: ^2.1.1
  dcli: ^1.5.7
  file: ^6.1.0
  glob: ^2.0.1
  html: ^0.15.0
  jinja: ^0.3.1
  markdown: ^4.0.0
  meta: ^1.3.0
  mime: ^1.0.0
  path: ^1.8.0
  petitparser: ^4.1.0
  process_run: ^0.12.1
  sass: ^1.35.1
  watcher: ^1.0.0
  xml: ^5.1.0
  yaml: ^3.1.0

dev_dependencies:
  grinder: ^0.9.0
  test: ^1.16.8
