name: blake
version: 0.1.0
description: Static Site Generator
homepage: https://github.com/vaetas/blake

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  ansicolor: ^1.0.5
  args: ^1.6.0
  markdown: ^3.0.0
  meta: ^1.2.3
  yaml: ^2.2.1
  yaml_edit: ^1.0.3

dev_dependencies:
  pedantic: ^1.9.2
