name: blake
version: 0.4.1
description: Experimental static site generator for Dart with Markdown support, Jinja templates and live-reload.
homepage: https://github.com/vaetas/blake

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  blake:

dependencies:
  ansicolor: ^2.0.1
  args: ^2.0.0
  dartz: ^0.9.2
  file: ^6.1.0
  glob: ^2.0.0
  html: ^0.15.0
  jinja: ^0.3.0
  markdown: ^4.0.0
  meta: ^1.3.0
  mime: ^1.0.0
  path: ^1.8.0
  petitparser: ^4.0.2
  process_run: ^0.12.1
  watcher: ^1.0.0
  xml: ^5.0.2
  yaml: ^3.1.0

dev_dependencies:
  analysis_options:
    git: https://github.com/vaetas/analysis_options.git
  test: ^1.16.8

scripts:
  compile:
    win:
      - mkdir build
      - dart2native bin/blake.dart -o build/blake.exe
    mac:
      - mkdir -p build
      - dart2native bin/blake.dart -o build/blake
      - cd build && tar -czf blake-mac.tar.gz blake
