name: blake
version: 0.1.0
description: Static Site Generator
homepage: https://github.com/vaetas/blake

environment:
  sdk: '>=2.8.0 <3.0.0'

executables:
  blake:

dependencies:
  ansicolor: ^1.0.5
  args: ^1.6.0
  html: ^0.14.0+4
  http_server: ^0.9.8+3
  logging: ^0.11.4
  markdown: ^3.0.0
  meta: ^1.2.3
  mustache_template: ^1.0.0+1
  path: ^1.7.0
  watcher: ^0.9.7+15
  yaml: ^2.2.1

dev_dependencies:
  pedantic: ^1.9.2
