name: blake
version: 0.1.0
description: Experimental static site generator for Dart with Markdown support, mustache templates and live-reload.
homepage: https://github.com/vaetas/blake

environment:
  sdk: '>=2.8.0 <3.0.0'

executables:
  blake:

dependencies:
  ansicolor: ^1.0.5
  args: ^1.6.0
  html: ^0.14.0+4
  http_server: ^0.9.8+3
  markdown: ^3.0.0
  meta: ^1.2.3
  mustache_template: ^1.0.0+1
  path: ^1.7.0
  watcher: ^0.9.7+15
  yaml: ^2.2.1

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.5

scripts:
  compile:
    win: dart2native bin\blake.dart -o bin\blake.exe
    mac:
      - mkdir -p build/mac
      - dart2native bin/blake.dart -o build/mac/blake
      - tar -czf build/mac/blake-mac.tar.gz build/mac/blake
